---
url: 'ssh://user@example.org:22'
timeout: 0.5
todo:
  extensions: ['torrent']
  mime_types: ['application/x-bittorrent']
locks:
  up: '/tmp/alluvion/up.lock'
  down: '/tmp/alluvion/down.lock'
paths:
  local:
    done: '/data/complete'
    todo: '/data/todo'
  remote:
    done: '/var/user/complete'
    todo: '/var/user/todo'
